### ISSUE TITLE
jupyter notebook中显示图时一片空白

### ISSUE THREAD

**Issue by wqw547243068** [pyecharts/pyecharts-users-cases#8]
执行以下代码，画出来的一片空白，智能render到html文件才行,怎么破？
```python
from pyecharts import Bar


attr = ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
v1 = [5, 20, 36, 10, 75, 90]
v2 = [10, 25, 8, 60, 20, 80]
bar = Bar("柱状图数据堆叠示例")
bar.add("商家A", attr, v1, is_stack=True)
bar.add("商家B", attr, v2, is_stack=True)

bar
```
执行环境：centos的server，python 2.7

**Comment by ghost** [comment]
同求解答

**Comment by BingoWon** [comment]
我是win10使用jupyter notebook, python 3.6, 最先运行ipynb文件时出现下面链接中的问题，并按照他的办法解决了，然后就出现了题目中的一片空白情况。求解！
https://blog.csdn.net/HYESC/article/details/83826464

**Comment by Kawayv** [comment]
执行报错
'Line3D' object has no attribute 'get_js_dependencies'
求解

**Comment by cilec** [comment]
没有安装地理位置依赖，具体可以参考官方文档的[faq](http://pyecharts.org/#/zh-cn/faq)

**Comment by mike1991** [comment]
I have the same problem.
environment:
Python version: 2.7.14 (default, Feb  6 2018, 20:03:13)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
pandas version: 0.24.2
matplotlib version: 2.1.1
NumPy version: 1.13.3
SciPy version: 1.0.0
IPython version: 5.5.0
scikit-learn version: 0.20.3
jupyter version: 1.0.0

Has anyone solved this problem??

**Comment by cilec** [comment]
应该是地图相关的库没有安装，可以看官方文档的常见问题，有解决方案

**Comment by xinhai-talk** [comment]
末尾加上bar.render_notebook()就可以了

**Comment by xliang10** [comment]
我遇到render_notebook()显示空白的原因是没有安装html5lib，仅供参考
